### ISSUE TITLE
version tags

### ISSUE THREAD

**Issue by zoechi** [nailgilaziev/msgpack#1]
Thanks for providing this package.

Because the versions tab on pub.dev does not work,
I next checked the tags in the GitHub repo, but they are not maintained.
It's usually a good idea to apply a tag with each release to pub.dev.

https://dev.to/neshaz/a-tutorial-for-tagging-releases-in-git-147e

**Comment by nailgilaziev** [comment]
Thanks! Done,  tags for previous versions created.
I will maintain them now)  
But what you mean by saying that "versions tab on pub.dev does not work"?

**Comment by zoechi** [comment]
That seems to be an issue on my machine/network - we are investigating.
Thanks for updating the tags!
